# Community Health Files
# https://docs.github.com/en/communities/setting-up-a-project-for-healthy-contributions/creating-a-default-community-health-file

# Issue Templates
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

# Pull Request Templates
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

# Code of Conduct
# https://docs.github.com/en/communities/setting-up-a-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project

# Contributing Guidelines
# https://docs.github.com/en/communities/setting-up-a-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

# Security Policy
# https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

# Support
# https://docs.github.com/en/communities/setting-up-a-project-for-healthy-contributions/adding-support-resources-to-your-project
