name: CI - Player Bespoke Audio Module

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Validate module.json
        run: |
          echo "🔍 Validating module.json..."

          # Check if module.json exists and is valid JSON
          if [ ! -f "module.json" ]; then
            echo "❌ module.json not found"
            exit 1
          fi

          # Validate JSON syntax
          if ! jq empty module.json 2>/dev/null; then
            echo "❌ module.json contains invalid JSON"
            exit 1
          fi

          # Check required fields
          REQUIRED_FIELDS=("id" "title" "description" "version" "compatibility" "scripts" "styles" "templates")
          for field in "${REQUIRED_FIELDS[@]}"; do
            if ! jq -e ".$field" module.json >/dev/null 2>&1; then
              echo "❌ module.json missing required field: $field"
              exit 1
            fi
          done

          echo "✅ module.json validation passed"

      - name: Validate file structure
        run: |
          echo "🔍 Validating file structure..."

          # Check required directories
          REQUIRED_DIRS=("scripts" "styles" "templates" "lang")
          for dir in "${REQUIRED_DIRS[@]}"; do
            if [ ! -d "$dir" ]; then
              echo "❌ Required directory not found: $dir"
              exit 1
            fi
          done

          # Check required files
          REQUIRED_FILES=(
            "scripts/player-bespoke-audio.js"
            "styles/player-bespoke-audio.css"
            "templates/audio-tab.hbs"
            "templates/gm-controls.hbs"
            "lang/en.json"
            "README.md"
            "CHANGELOG.md"
          )

          for file in "${REQUIRED_FILES[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Required file not found: $file"
              exit 1
            fi
          done

          echo "✅ File structure validation passed"

      - name: Validate JavaScript syntax
        run: |
          echo "🔍 Validating JavaScript syntax..."

          # Check if main script file has valid syntax
          if ! node -c scripts/player-bespoke-audio.js; then
            echo "❌ JavaScript syntax error in main script"
            exit 1
          fi

          echo "✅ JavaScript syntax validation passed"

      - name: Validate CSS syntax
        run: |
          echo "🔍 Validating CSS syntax..."

          # Basic CSS validation (check for obvious syntax errors)
          if grep -q "{" styles/player-bespoke-audio.css && grep -q "}" styles/player-bespoke-audio.css; then
            echo "✅ CSS syntax validation passed"
          else
            echo "❌ CSS syntax validation failed"
            exit 1
          fi

      - name: Validate Handlebars templates
        run: |
          echo "🔍 Validating Handlebars templates..."

          # Check for basic Handlebars syntax
          for template in templates/*.hbs; do
            if [ -f "$template" ]; then
              # Check for basic Handlebars syntax patterns
              if grep -q "{{" "$template" || grep -q "}}" "$template"; then
                echo "✅ Template $template validation passed"
              else
                echo "⚠️  Template $template has no Handlebars syntax (may be intentional)"
              fi
            fi
          done

      - name: Check file sizes
        run: |
          echo "🔍 Checking file sizes..."

          # Check for reasonable file sizes
          MAX_SIZE=1048576  # 1MB

          for file in scripts/*.js styles/*.css templates/*.hbs; do
            if [ -f "$file" ]; then
              size=$(stat -c%s "$file" 2>/dev/null || stat -f%z "$file" 2>/dev/null)
              if [ "$size" -gt "$MAX_SIZE" ]; then
                echo "⚠️  Large file detected: $file ($size bytes)"
              else
                echo "✅ File size OK: $file ($size bytes)"
              fi
            fi
          done

      - name: Run tests
        run: |
          echo "🧪 Running tests..."

          # Run the test page if it exists
          if [ -f "test-upload.html" ]; then
            echo "✅ Test page found: test-upload.html"
          else
            echo "⚠️  No test page found"
          fi

          # Run npm test if configured
          if npm run test 2>/dev/null; then
            echo "✅ NPM tests passed"
          else
            echo "ℹ️  No NPM tests configured"
          fi

      - name: Create validation report
        run: |
          echo "📋 Creating validation report..."

          echo "# Module Validation Report" > validation-report.md
          echo "Generated: $(date)" >> validation-report.md
          echo "" >> validation-report.md

          echo "## File Structure" >> validation-report.md
          echo "- ✅ module.json: Valid" >> validation-report.md
          echo "- ✅ Required directories: Present" >> validation-report.md
          echo "- ✅ Required files: Present" >> validation-report.md
          echo "" >> validation-report.md

          echo "## Code Quality" >> validation-report.md
          echo "- ✅ JavaScript: Syntax valid" >> validation-report.md
          echo "- ✅ CSS: Syntax valid" >> validation-report.md
          echo "- ✅ Templates: Handlebars syntax present" >> validation-report.md
          echo "" >> validation-report.md

          echo "## Module Ready for Release" >> validation-report.md
          echo "All validation checks passed successfully!" >> validation-report.md

          echo "✅ Validation report created: validation-report.md"

      - name: Upload validation report
        uses: actions/upload-artifact@v3
        with:
          name: validation-report
          path: validation-report.md

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run security audit
        run: |
          echo "🔒 Running security audit..."

          # Check for known vulnerabilities in dependencies
          if [ -f "package.json" ]; then
            npm audit --audit-level moderate || true
          else
            echo "ℹ️  No package.json found, skipping npm audit"
          fi

          # Check for sensitive information in code
          echo "🔍 Checking for sensitive information..."

          # Check for hardcoded API keys, passwords, etc.
          if grep -r -i "api_key\|password\|secret\|token" . --exclude-dir=.git --exclude=*.md; then
            echo "⚠️  Potential sensitive information found in code"
          else
            echo "✅ No obvious sensitive information found"
          fi

          echo "🔒 Security audit completed"

  documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate documentation
        run: |
          echo "📚 Validating documentation..."

          # Check README
          if [ -f "README.md" ]; then
            echo "✅ README.md found"
            
            # Check for basic sections
            if grep -q "## Installation" README.md; then
              echo "✅ Installation section found"
            else
              echo "⚠️  Installation section missing"
            fi
            
            if grep -q "## Usage" README.md; then
              echo "✅ Usage section found"
            else
              echo "⚠️  Usage section missing"
            fi
            
          else
            echo "❌ README.md not found"
            exit 1
          fi

          # Check CHANGELOG
          if [ -f "CHANGELOG.md" ]; then
            echo "✅ CHANGELOG.md found"
          else
            echo "⚠️  CHANGELOG.md not found"
          fi

          echo "📚 Documentation validation completed"
